/**
 * @file latex_report.cpp
 * @brief Comprehensive LaTeX report generator for CoolSolve.
 *
 * Produces a self-contained .tex document with model equations, solved
 * variable values, block structure, and solver statistics.  The backend
 * only generates LaTeX source — compilation to PDF is handled by the
 * frontend (GUI) or by the user directly.
 */

#include "coolsolve/latex_report.h"
#include "coolsolve/constants.h"
#include <fstream>
#include <sstream>
#include <iomanip>
#include <chrono>
#include <ctime>
#include <cmath>
#include <algorithm>

namespace coolsolve {

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/// Escape special LaTeX characters in plain text (not math mode).
static std::string escLatex(const std::string& s) {
    std::string out;
    out.reserve(s.size() * 2);
    for (char c : s) {
        switch (c) {
            case '&':  out += "\\&";  break;
            case '%':  out += "\\%";  break;
            case '$':  out += "\\$";  break;
            case '#':  out += "\\#";  break;
            case '_':  out += "\\_";  break;
            case '{':  out += "\\{";  break;
            case '}':  out += "\\}";  break;
            case '~':  out += "\\textasciitilde{}"; break;
            case '^':  out += "\\textasciicircum{}"; break;
            case '\\': out += "\\textbackslash{}"; break;
            default:   out += c;
        }
    }
    return out;
}

/// Format a floating-point number for display in a LaTeX table cell.
static std::string fmtVal(double v) {
    if (std::isnan(v)) return "NaN";
    if (std::isinf(v)) return (v > 0) ? "$+\\infty$" : "$-\\infty$";
    // Use fixed notation for "human-sized" numbers, scientific otherwise
    std::ostringstream oss;
    if (std::abs(v) >= 1e-2 && std::abs(v) < 1e6) {
        oss << std::fixed << std::setprecision(4) << v;
    } else if (v == 0.0) {
        oss << "0";
    } else {
        oss << std::scientific << std::setprecision(4) << v;
    }
    return oss.str();
}

/// Generate a timestamp string.
static std::string timestamp() {
    auto now = std::chrono::system_clock::now();
    auto t = std::chrono::system_clock::to_time_t(now);
    std::string ts = std::ctime(&t);
    if (!ts.empty() && ts.back() == '\n') ts.pop_back();
    return ts;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

std::string generateLatexReport(
    const IR& ir,
    const StructuralAnalysisResult& analysis,
    const SolveResult& solveResult,
    const CoolSolveRunner::PipelineTiming& timing,
    const std::string& modelName,
    const std::string& inputFile)
{
    std::ostringstream tex;

    // ===== Document preamble ================================================
    tex << "% CoolSolve LaTeX Report — auto-generated, do not edit by hand\n";
    tex << "\\documentclass[11pt,a4paper]{article}\n";
    tex << "\\usepackage[utf8]{inputenc}\n";
    tex << "\\usepackage[T1]{fontenc}\n";
    tex << "\\usepackage{lmodern}\n";
    tex << "\\usepackage{amsmath,amssymb}\n";
    tex << "\\usepackage{booktabs}\n";
    tex << "\\usepackage{longtable}\n";
    tex << "\\usepackage{geometry}\n";
    tex << "\\usepackage{hyperref}\n";
    tex << "\\usepackage{xcolor}\n";
    tex << "\\usepackage{graphicx}\n";
    tex << "\\usepackage{fancyhdr}\n";
    tex << "\\usepackage{enumitem}\n";
    tex << "\\usepackage{caption}\n";
    tex << "\\geometry{margin=2.5cm}\n";
    tex << "\\hypersetup{colorlinks=true,linkcolor=blue!60!black,urlcolor=blue!60!black}\n\n";

    // Header / footer
    tex << "\\pagestyle{fancy}\n";
    tex << "\\fancyhf{}\n";
    tex << "\\fancyhead[L]{\\textsc{CoolSolve Report}}\n";
    tex << "\\fancyhead[R]{" << escLatex(modelName.empty() ? "Untitled Model" : modelName) << "}\n";
    tex << "\\fancyfoot[C]{\\thepage}\n";
    tex << "\\renewcommand{\\headrulewidth}{0.4pt}\n\n";

    // Custom colours for table zebra-striping
    tex << "\\definecolor{blockbg}{gray}{0.95}\n\n";

    // ===== Title ============================================================
    tex << "\\begin{document}\n\n";
    tex << "\\begin{center}\n";
    tex << "  {\\LARGE\\bfseries CoolSolve Analysis Report}\\\\[6pt]\n";
    tex << "  {\\large " << escLatex(modelName.empty() ? "Untitled Model" : modelName) << "}\\\\[4pt]\n";
    tex << "  {\\small Generated by CoolSolve --- " << escLatex(timestamp()) << "}\n";
    tex << "\\end{center}\n";
    tex << "\\vspace{1em}\n";
    tex << "\\noindent\\rule{\\textwidth}{0.4pt}\n";
    tex << "\\tableofcontents\n";
    tex << "\\vspace{1em}\n\n";

    // ===== Section 1: Model Overview ========================================
    tex << "\\section{Model Overview}\n\n";
    tex << "This report summarises the structural analysis and numerical solution of the\n";
    tex << "equation system defined in \\texttt{" << escLatex(inputFile) << "}.\n";
    tex << "CoolSolve decomposes the system into topologically ordered blocks, solves each\n";
    tex << "block using the configured solver pipeline, and verifies the solution.\n\n";

    tex << "\\begin{table}[h!]\n";
    tex << "\\centering\n";
    tex << "\\caption{Model statistics}\n";
    tex << "\\begin{tabular}{lr}\n";
    tex << "\\toprule\n";
    tex << "\\textbf{Metric} & \\textbf{Value} \\\\\n";
    tex << "\\midrule\n";
    tex << "Equations & " << ir.getEquationCount() << " \\\\\n";
    tex << "Variables & " << ir.getNonConstantVariableCount() << " \\\\\n";
    tex << "Square system & " << (ir.isSquare() ? "Yes" : "No") << " \\\\\n";
    tex << "Total blocks & " << analysis.totalBlocks << " \\\\\n";
    tex << "Largest block & " << analysis.largestBlockSize << " \\\\\n";
    tex << "Explicit equations & " << analysis.explicitEquationCount << " \\\\\n";

    // Symbolic reduction summary
    {
        int blocksReduced = 0, varsEliminated = 0;
        for (const auto& br : solveResult.blockResults) {
            if (br.symbolicReductionApplied) {
                ++blocksReduced;
                varsEliminated += (br.originalSize - br.reducedSize);
            }
        }
        if (blocksReduced > 0) {
            tex << "Blocks reduced (symbolic) & " << blocksReduced << " \\\\\n";
            tex << "Variables eliminated & " << varsEliminated << " \\\\\n";
        }
    }

    // Solver status
    if (solveResult.success) {
        tex << "Solver status & \\textcolor{green!60!black}{SUCCESS} \\\\\n";
    } else {
        tex << "Solver status & \\textcolor{red}{" << escLatex(statusToString(solveResult.status)) << "} \\\\\n";
    }
    tex << "Total iterations & " << solveResult.totalIterations << " \\\\\n";
    tex << "\\bottomrule\n";
    tex << "\\end{tabular}\n";
    tex << "\\end{table}\n\n";

    // ===== Section 2: Equations =============================================
    tex << "\\section{Equations}\n\n";
    tex << "The following equations define the model.\n\n";

    for (const auto& eq : ir.getEquations()) {
        // Skip string-variable assignments (e.g. fluid$='Water') — not math
        if (eq.lhs && eq.lhs->is<Variable>()) {
            const auto& varName = eq.lhs->as<Variable>().flattenedName();
            if (!varName.empty() && varName.back() == '$') continue;
        }

        // Display preceding "" comments as bold paragraph text
        for (const auto& cmt : eq.precedingComments) {
            tex << "\\noindent\\textbf{" << escLatex(cmt) << "}\n\\medskip\n\n";
        }

        tex << "\\begin{equation}\n";
        tex << expressionToLatex(eq.lhs) << " = " << expressionToLatex(eq.rhs) << "\n";
        tex << "\\end{equation}\n";

        // Display inline "" comment as a note below the equation
        if (!eq.inlineComment.empty()) {
            tex << "\\noindent\\textit{" << escLatex(eq.inlineComment) << "}\n\\smallskip\n\n";
        }
    }
    tex << "\n";

    // ===== Section 3: Variable Solutions ====================================
    tex << "\\section{Variable Solutions}\n\n";
    tex << "Table~\\ref{tab:solutions} lists all solved variable values together with\n";
    tex << "their units and inferred thermodynamic role (if any).\n\n";

    tex << "\\begin{longtable}{lrrll}\n";
    tex << "\\caption{Solved variable values}\\label{tab:solutions}\\\\\n";
    tex << "\\toprule\n";
    tex << "\\textbf{Variable} & \\textbf{Value} & \\textbf{Units} & \\textbf{Property} & \\textbf{Fluid} \\\\\n";
    tex << "\\midrule\n";
    tex << "\\endfirsthead\n";
    tex << "\\toprule\n";
    tex << "\\textbf{Variable} & \\textbf{Value} & \\textbf{Units} & \\textbf{Property} & \\textbf{Fluid} \\\\\n";
    tex << "\\midrule\n";
    tex << "\\endhead\n";
    tex << "\\bottomrule\n";
    tex << "\\endfoot\n";

    for (const auto& [name, info] : ir.getVariables()) {
        // Skip built-in constants from the table
        if (Constants::isConstant(name)) continue;

        tex << "$" << info.latexLabel << "$ & ";

        // Value
        auto valIt = solveResult.variables.find(name);
        auto strIt = solveResult.stringVariables.find(name);
        if (valIt != solveResult.variables.end()) {
            tex << fmtVal(valIt->second);
        } else if (strIt != solveResult.stringVariables.end()) {
            tex << "\\texttt{" << escLatex(strIt->second) << "}";
        } else if (info.solutionValue) {
            tex << fmtVal(*info.solutionValue);
        } else {
            tex << "---";
        }

        tex << " & " << escLatex(info.units);
        tex << " & " << escLatex(info.inferredProperty);
        tex << " & " << escLatex(info.inferredFluid);
        tex << " \\\\\n";
    }
    tex << "\\end{longtable}\n\n";

    // ===== Section 4: Plots ================================================
    // The GUI frontend exports Plotly charts as PNG images and uploads them
    // to the compile endpoint.  Each image gets an \\IfFileExists guard so
    // the .tex also compiles standalone (without images).
    tex << "\\section{Plots}\n\n";
    tex << "Thermodynamic diagrams and parametric study plots (if any) are generated\n";
    tex << "by the CoolSolve GUI and inserted below when the report is compiled.\n\n";

    tex << "% --- Thermodynamic diagrams (inserted by GUI) ---\n";
    tex << "\\IfFileExists{thermo_diagrams.png}{%\n";
    tex << "  \\begin{figure}[h!]\n";
    tex << "  \\centering\n";
    tex << "  \\includegraphics[width=0.92\\textwidth]{thermo_diagrams.png}\n";
    tex << "  \\caption{Thermodynamic state-point diagram}\n";
    tex << "  \\end{figure}\n";
    tex << "}{}\n\n";

    tex << "% --- Parametric study plots (inserted by GUI) ---\n";
    tex << "% One figure per uploaded parametric plot image.\n";
    tex << "\\newcounter{paramplot}\n";
    tex << "\\loop\\stepcounter{paramplot}\n";
    tex << "  \\IfFileExists{parametric_\\theparamplot.png}{%\n";
    tex << "    \\begin{figure}[h!]\n";
    tex << "    \\centering\n";
    tex << "    \\includegraphics[width=0.92\\textwidth]{parametric_\\theparamplot.png}\n";
    tex << "    \\caption{Parametric study \\theparamplot}\n";
    tex << "    \\end{figure}\n";
    tex << "  }{}\n";
    tex << "\\ifnum\\value{paramplot}<20\\repeat\n\n";

    // ===== End ==============================================================
    tex << "\\end{document}\n";

    return tex.str();
}

bool writeLatexReport(
    const std::string& outputPath,
    const IR& ir,
    const StructuralAnalysisResult& analysis,
    const SolveResult& solveResult,
    const CoolSolveRunner::PipelineTiming& timing,
    const std::string& modelName,
    const std::string& inputFile)
{
    std::ofstream f(outputPath);
    if (!f.is_open()) return false;
    f << generateLatexReport(ir, analysis, solveResult, timing, modelName, inputFile);
    return f.good();
}

}  // namespace coolsolve
