# embed_assets.cmake
# Generates C++ source files that embed the frontend GUI assets as binary data.
# Usage (called from CMakeLists.txt at configure time):
#   cmake -DGUI_DIST_DIR=<path> -DOUTPUT_CPP=<path> -DOUTPUT_H=<path>
#         [-DEXTRA_DIRS=<dir1>|<prefix1>;<dir2>|<prefix2>;...]
#         -P embed_assets.cmake
#
# EXTRA_DIRS is a semicolon-separated list of "<absolute-dir>|<url-prefix>" pairs.
# Files in <absolute-dir> are embedded under "/<url-prefix>/<relative-path>".
# Example:
#   -DEXTRA_DIRS="/repo/docs|docs;/repo|."
# embeds /repo/docs/*.md under /docs/... and /repo/README.md under /README.md.

if(NOT GUI_DIST_DIR OR NOT OUTPUT_CPP OR NOT OUTPUT_H)
    message(FATAL_ERROR "embed_assets.cmake requires GUI_DIST_DIR, OUTPUT_CPP, OUTPUT_H")
endif()

# Collect all files recursively from GUI dist
file(GLOB_RECURSE ASSET_FILES RELATIVE "${GUI_DIST_DIR}" "${GUI_DIST_DIR}/*")
list(SORT ASSET_FILES)

# Start building the header
set(HEADER_CONTENT [=[
// Auto-generated by embed_assets.cmake — do not edit
#pragma once
#include <string>
#include <unordered_map>

struct EmbeddedAsset {
    const unsigned char* data;
    unsigned int size;
    const char* mimeType;
};

// Returns nullptr if path not found
const EmbeddedAsset* getEmbeddedAsset(const std::string& path);

]=])

# Start building the source
set(SOURCE_CONTENT [=[
// Auto-generated by embed_assets.cmake — do not edit
#include "embedded_assets.h"

]=])

# Helper: guess MIME type from extension
function(guess_mime_type FILENAME OUT_VAR)
    get_filename_component(EXT "${FILENAME}" LAST_EXT)
    string(TOLOWER "${EXT}" EXT)
    if(EXT STREQUAL ".html")
        set(${OUT_VAR} "text/html" PARENT_SCOPE)
    elseif(EXT STREQUAL ".css")
        set(${OUT_VAR} "text/css" PARENT_SCOPE)
    elseif(EXT STREQUAL ".js")
        set(${OUT_VAR} "application/javascript" PARENT_SCOPE)
    elseif(EXT STREQUAL ".json")
        set(${OUT_VAR} "application/json" PARENT_SCOPE)
    elseif(EXT STREQUAL ".svg")
        set(${OUT_VAR} "image/svg+xml" PARENT_SCOPE)
    elseif(EXT STREQUAL ".png")
        set(${OUT_VAR} "image/png" PARENT_SCOPE)
    elseif(EXT STREQUAL ".ico")
        set(${OUT_VAR} "image/x-icon" PARENT_SCOPE)
    elseif(EXT STREQUAL ".woff")
        set(${OUT_VAR} "font/woff" PARENT_SCOPE)
    elseif(EXT STREQUAL ".woff2")
        set(${OUT_VAR} "font/woff2" PARENT_SCOPE)
    elseif(EXT STREQUAL ".ttf")
        set(${OUT_VAR} "font/ttf" PARENT_SCOPE)
    elseif(EXT STREQUAL ".map")
        set(${OUT_VAR} "application/json" PARENT_SCOPE)
    else()
        set(${OUT_VAR} "application/octet-stream" PARENT_SCOPE)
    endif()
endfunction()

# Generate data arrays for each file
set(ASSET_INDEX 0)
set(MAP_ENTRIES "")

foreach(ASSET_FILE ${ASSET_FILES})
    set(FULL_PATH "${GUI_DIST_DIR}/${ASSET_FILE}")
    
    # Read file as hex
    file(READ "${FULL_PATH}" FILE_HEX HEX)
    
    # Get file size
    file(SIZE "${FULL_PATH}" FILE_SIZE)
    
    # Fast conversion: use regex to insert 0x prefix and commas in one pass
    # "aabb" -> "0xaa,0xbb"
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," FILE_HEX "${FILE_HEX}")
    # Remove trailing comma
    string(REGEX REPLACE ",$" "" FILE_HEX "${FILE_HEX}")
    # Add line breaks every ~16 values for readability (optional, skip for speed)
    
    # Add a null terminator so text assets can be used as C strings
    string(APPEND FILE_HEX ",0x00")
    
    # Create a valid C identifier from the file path
    string(MAKE_C_IDENTIFIER "asset_${ASSET_FILE}" VAR_NAME)
    
    # Guess MIME type
    guess_mime_type("${ASSET_FILE}" MIME)
    
    # Append the data array to source
    string(APPEND SOURCE_CONTENT "static const unsigned char ${VAR_NAME}[] = {\n    ${FILE_HEX}\n};\n\n")
    
    # Build map entry (use / prefix for URL matching)
    string(APPEND MAP_ENTRIES "    {\"/${ASSET_FILE}\", {${VAR_NAME}, ${FILE_SIZE}, \"${MIME}\"}},\n")
    
    math(EXPR ASSET_INDEX "${ASSET_INDEX} + 1")
endforeach()

# ----------------------------------------------------------------
# Embed extra directories passed as numbered pairs:
#   EXTRA_DIR1 / EXTRA_PREFIX1, EXTRA_DIR2 / EXTRA_PREFIX2, …
# Files in EXTRA_DIRn are embedded under "/<EXTRA_PREFIXn>/<filename>".
# A prefix of "." means files are embedded at "/<filename>" (root level).
# ----------------------------------------------------------------
set(EXTRA_INDEX 1)
while(1)
    set(EKEY "EXTRA_DIR${EXTRA_INDEX}")
    set(PKEY "EXTRA_PREFIX${EXTRA_INDEX}")
    if(NOT DEFINED ${EKEY})
        break()
    endif()
    set(EXTRA_DIR "${${EKEY}}")
    set(URL_PREFIX "${${PKEY}}")

    if(NOT EXISTS "${EXTRA_DIR}")
        message(WARNING "embed_assets.cmake: extra dir '${EXTRA_DIR}' does not exist, skipping")
        math(EXPR EXTRA_INDEX "${EXTRA_INDEX} + 1")
        continue()
    endif()

    file(GLOB EXTRA_FILES_FLAT "${EXTRA_DIR}/*")
    list(SORT EXTRA_FILES_FLAT)

    foreach(FULL_PATH ${EXTRA_FILES_FLAT})
        if(IS_DIRECTORY "${FULL_PATH}")
            continue()
        endif()
        get_filename_component(FNAME "${FULL_PATH}" NAME)
        # Skip lock/temp files
        if(FNAME MATCHES "^\.~")
            continue()
        endif()
        # When embedding the repo root, only take README.md
        if("${URL_PREFIX}" STREQUAL "." AND NOT FNAME STREQUAL "README.md")
            continue()
        endif()

        # Build the URL path
        if("${URL_PREFIX}" STREQUAL ".")
            set(URL_PATH "/${FNAME}")
        else()
            set(URL_PATH "/${URL_PREFIX}/${FNAME}")
        endif()

        file(READ "${FULL_PATH}" FILE_HEX HEX)
        file(SIZE "${FULL_PATH}" FILE_SIZE)
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," FILE_HEX "${FILE_HEX}")
        string(REGEX REPLACE ",$" "" FILE_HEX "${FILE_HEX}")
        string(APPEND FILE_HEX ",0x00")

        string(MAKE_C_IDENTIFIER "extraasset_${EXTRA_INDEX}_${FNAME}" VAR_NAME)
        guess_mime_type("${FNAME}" MIME)
        # Override MIME for markdown
        if(FNAME MATCHES "\.md$")
            set(MIME "text/plain; charset=utf-8")
        endif()

        string(APPEND SOURCE_CONTENT "static const unsigned char ${VAR_NAME}[] = {\n    ${FILE_HEX}\n};\n\n")
        string(APPEND MAP_ENTRIES "    {\"${URL_PATH}\", {${VAR_NAME}, ${FILE_SIZE}, \"${MIME}\"}},\n")
        math(EXPR ASSET_INDEX "${ASSET_INDEX} + 1")
    endforeach()

    math(EXPR EXTRA_INDEX "${EXTRA_INDEX} + 1")
endwhile()

# Build the lookup function
string(APPEND SOURCE_CONTENT "static const std::unordered_map<std::string, EmbeddedAsset> embeddedAssets = {\n")
string(APPEND SOURCE_CONTENT "${MAP_ENTRIES}")
string(APPEND SOURCE_CONTENT "};\n\n")

string(APPEND SOURCE_CONTENT [=[
const EmbeddedAsset* getEmbeddedAsset(const std::string& path) {
    auto it = embeddedAssets.find(path);
    if (it != embeddedAssets.end()) {
        return &it->second;
    }
    return nullptr;
}
]=])

# Write output files
file(WRITE "${OUTPUT_CPP}" "${SOURCE_CONTENT}")
file(WRITE "${OUTPUT_H}" "${HEADER_CONTENT}")

message(STATUS "Embedded ${ASSET_INDEX} frontend assets into ${OUTPUT_CPP}")
