# embed_assets.cmake
# Generates C++ source files that embed the frontend GUI assets as binary data.
# Usage (called from CMakeLists.txt at configure time):
#   cmake -DGUI_DIST_DIR=<path> -DOUTPUT_CPP=<path> -DOUTPUT_H=<path> -P embed_assets.cmake

if(NOT GUI_DIST_DIR OR NOT OUTPUT_CPP OR NOT OUTPUT_H)
    message(FATAL_ERROR "embed_assets.cmake requires GUI_DIST_DIR, OUTPUT_CPP, OUTPUT_H")
endif()

# Collect all files recursively
file(GLOB_RECURSE ASSET_FILES RELATIVE "${GUI_DIST_DIR}" "${GUI_DIST_DIR}/*")
list(SORT ASSET_FILES)

# Start building the header
set(HEADER_CONTENT [=[
// Auto-generated by embed_assets.cmake — do not edit
#pragma once
#include <string>
#include <unordered_map>

struct EmbeddedAsset {
    const unsigned char* data;
    unsigned int size;
    const char* mimeType;
};

// Returns nullptr if path not found
const EmbeddedAsset* getEmbeddedAsset(const std::string& path);

]=])

# Start building the source
set(SOURCE_CONTENT [=[
// Auto-generated by embed_assets.cmake — do not edit
#include "embedded_assets.h"

]=])

# Helper: guess MIME type from extension
function(guess_mime_type FILENAME OUT_VAR)
    get_filename_component(EXT "${FILENAME}" EXT)
    string(TOLOWER "${EXT}" EXT)
    if(EXT STREQUAL ".html")
        set(${OUT_VAR} "text/html" PARENT_SCOPE)
    elseif(EXT STREQUAL ".css")
        set(${OUT_VAR} "text/css" PARENT_SCOPE)
    elseif(EXT STREQUAL ".js")
        set(${OUT_VAR} "application/javascript" PARENT_SCOPE)
    elseif(EXT STREQUAL ".json")
        set(${OUT_VAR} "application/json" PARENT_SCOPE)
    elseif(EXT STREQUAL ".svg")
        set(${OUT_VAR} "image/svg+xml" PARENT_SCOPE)
    elseif(EXT STREQUAL ".png")
        set(${OUT_VAR} "image/png" PARENT_SCOPE)
    elseif(EXT STREQUAL ".ico")
        set(${OUT_VAR} "image/x-icon" PARENT_SCOPE)
    elseif(EXT STREQUAL ".woff")
        set(${OUT_VAR} "font/woff" PARENT_SCOPE)
    elseif(EXT STREQUAL ".woff2")
        set(${OUT_VAR} "font/woff2" PARENT_SCOPE)
    elseif(EXT STREQUAL ".ttf")
        set(${OUT_VAR} "font/ttf" PARENT_SCOPE)
    elseif(EXT STREQUAL ".map")
        set(${OUT_VAR} "application/json" PARENT_SCOPE)
    else()
        set(${OUT_VAR} "application/octet-stream" PARENT_SCOPE)
    endif()
endfunction()

# Generate data arrays for each file
set(ASSET_INDEX 0)
set(MAP_ENTRIES "")

foreach(ASSET_FILE ${ASSET_FILES})
    set(FULL_PATH "${GUI_DIST_DIR}/${ASSET_FILE}")
    
    # Read file as hex
    file(READ "${FULL_PATH}" FILE_HEX HEX)
    
    # Get file size
    file(SIZE "${FULL_PATH}" FILE_SIZE)
    
    # Convert hex string to comma-separated 0xNN bytes
    string(LENGTH "${FILE_HEX}" HEX_LEN)
    set(BYTE_ARRAY "")
    set(LINE_BYTES 0)
    math(EXPR LAST_POS "${HEX_LEN} - 2")
    
    foreach(POS RANGE 0 ${LAST_POS} 2)
        string(SUBSTRING "${FILE_HEX}" ${POS} 2 BYTE)
        if(LINE_BYTES GREATER 0)
            string(APPEND BYTE_ARRAY ",")
        endif()
        if(LINE_BYTES EQUAL 16)
            string(APPEND BYTE_ARRAY "\n    ")
            set(LINE_BYTES 0)
        endif()
        string(APPEND BYTE_ARRAY "0x${BYTE}")
        math(EXPR LINE_BYTES "${LINE_BYTES} + 1")
    endforeach()
    
    # Add a null terminator so text assets can be used as C strings
    if(LINE_BYTES GREATER 0)
        string(APPEND BYTE_ARRAY ",")
    endif()
    string(APPEND BYTE_ARRAY "0x00")
    
    # Create a valid C identifier from the file path
    string(MAKE_C_IDENTIFIER "asset_${ASSET_FILE}" VAR_NAME)
    
    # Guess MIME type
    guess_mime_type("${ASSET_FILE}" MIME)
    
    # Append the data array to source
    string(APPEND SOURCE_CONTENT "static const unsigned char ${VAR_NAME}[] = {\n    ${BYTE_ARRAY}\n};\n\n")
    
    # Build map entry (use / prefix for URL matching)
    string(APPEND MAP_ENTRIES "    {\"/${ASSET_FILE}\", {${VAR_NAME}, ${FILE_SIZE}, \"${MIME}\"}},\n")
    
    math(EXPR ASSET_INDEX "${ASSET_INDEX} + 1")
endforeach()

# Build the lookup function
string(APPEND SOURCE_CONTENT "static const std::unordered_map<std::string, EmbeddedAsset> embeddedAssets = {\n")
string(APPEND SOURCE_CONTENT "${MAP_ENTRIES}")
string(APPEND SOURCE_CONTENT "};\n\n")

string(APPEND SOURCE_CONTENT [=[
const EmbeddedAsset* getEmbeddedAsset(const std::string& path) {
    auto it = embeddedAssets.find(path);
    if (it != embeddedAssets.end()) {
        return &it->second;
    }
    return nullptr;
}
]=])

# Write output files
file(WRITE "${OUTPUT_CPP}" "${SOURCE_CONTENT}")
file(WRITE "${OUTPUT_H}" "${HEADER_CONTENT}")

message(STATUS "Embedded ${ASSET_INDEX} frontend assets into ${OUTPUT_CPP}")
